services:
  samba: 
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    stdin_open: true
    tty: true 
    environment:
      TZ: Europe/Berlin

      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: true

      # add a single user. If you need more, use command instead of environment
      # required arg: "<username>;<passwd>"
      # <username> for user
      # <password> for user
      # [ID] for user, default: ""
      # [group] for user, default: ""
      # Define useres in a file called environment file (.env) to secure the passwords...
      USER: "${USER1}"
      USER2: "${USER2}"

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      SHARE: Homeserver;/srv;yes;no;no;sorkallaf;admin

      # workgroup/domain name for share default: "MYGROUP"
      # WORKGROUP: "Homeserver"

      PERMISSIONS: true

    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /srv/samba:/srv/:z # :z allows share to be used by multiple containers
